site_name: 'My Project Docs'

site_url: 'https://username.github.io/myproject/'

theme:
  name: 'readthedocs'
  language: 'ru'  # если нужно

nav:
 - Главная: index.md
 - API: api_reference.md
 - Пример ноутбука: module_example.ipynb
plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true