site_name: 'My Project Docs'

site_url: 'https://username.github.io/myproject/'

theme:
  name: 'material'
  language: 'ru'  
  version:
    provider: mike
nav:
 - Главная: index.md
 - API: api_reference.md
 # - Пример ноутбука: module_example.ipynb
plugins:
  #- mkdocs_jupyter
  - mkdocstrings:
      default_handler: python
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true